### PR TITLE
updated t-sql code

### PR DESCRIPTION
**Pull request by afurmanchuk**
pregnancy exclusion criteria take out all encounters within pregnancy
time frame

### CODE REVIEW

**Comment by dckc** [comment]
Changing the filename makes it look like this is all new code, but I suspect you only changed part of the code.

Is anybody near you familiar with git?

**Comment by dckc** [comment]
Normal diff tools can't find any code in common between the Dec 1 version (e84939e) and this version. As far as I can tell with tools, you completely rewrote the code. Did all of the logic really change?

**Comment by afurmanchuk** [comment]
Did i do it wrong? I made local clone on my computer, than committed new upload.  I requested pull from master.  Someone was guiding me to do this way. Supposed to work. You cannot see it yet?

I will do comparison between old oracle  and new sql this weekend. It should have difference at beginning because i introduced variable for age and exclusion of all records based on pregnancy time frame. I did exclusion in postprocessing before. Current code will produce clean study and DM sample right away. People could use it for extracting variable without the need of post processing step. The rest of the code should be the same.

**Comment by dckc** [comment]
I can see the new code. But this commit (d9782dc) has no parent; i.e. it shares no history with the rest of the project. I don't think that's what you meant. It sounds like you meant to commit against some recent version of master.

**Comment by dckc** [comment]
oops... now I see it has a parent: b541695 ... ok... that makes a little more sense...

**Comment by afurmanchuk** [comment]
I am glad i finally did something useful with github. 
We will discuss new code in today's meeting. And after weekend i will be ready to propose changes to oracle.

**Comment by dckc** [comment]
I'm able to use tools to see the changes now that I normalized the newlines to CRLF: 3050656.

Previous to that commit is 99937e7, which renames `NextDextractionCode_12.1.16.sql` -> `NextDcodeForTable1_studyAndDMsampleExtraction.sql`. The result is similar to `NextDcodeForTable1_studyAndDMsampleExtraction-2017-04-05-AF.sql` that you proposed, but when using version control, date and author info doesn't belong in the filename.

I merged this revised history into 1f1c621.

We need to make sure you disregard d9782dc and work from 1f1c621.

**Pull request closed without merging**
